In [59]:
import numpy as np

# numpy array

In [60]:
benimListem = [10,20,30,40]

In [61]:
np.array(benimListem)

array([10, 20, 30, 40])

In [62]:
matrixListesi = [[10,20,30],[40,50,60],[70,80,90]]

In [63]:
matrixListesi

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [64]:
matrixListesi[1][2]

60

In [65]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# arange

In [66]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [71]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [72]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace

In [73]:
np.linspace(0,10,5)
#(Starting index, Stopping index, Number Of Elements)
#Başlangıç indeksinden bitiş indekse kadar eşit aralık olacak şekilde belirtilen elemanlı bir dizi oluşturur

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [74]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [75]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [76]:
np.linspace(0,30,50)

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

# eye

In [77]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

In [78]:
np.random.randn(5)

array([-0.0600967 ,  0.6692183 , -1.52543133,  1.65769194,  1.25433736])

In [79]:
np.random.randn(4,4)

array([[-1.41707423,  0.43150869, -0.41462208,  1.65849196],
       [-0.84565163,  1.02044942,  1.62433633, -1.31851436],
       [ 1.54322858, -0.41277871,  0.36934652,  1.20415792],
       [ 0.1065661 ,  1.47286702,  0.9775495 , -0.5115008 ]])

In [80]:
np.random.randint(1,15)

8

In [81]:
np.random.randint(1,100,6)

array([86, 90, 82, 46, 74, 61])

In [82]:
benimNumpyDizim = np.arange(30)

In [83]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [84]:
benimRandomDizim = np.random.randint(0,100,10)

In [85]:
benimRandomDizim

array([22, 18, 78, 38, 22, 59, 52, 43,  6, 81])

# dizi methodları

In [86]:
benimNumpyDizim.reshape(5,6)
#2,15 5,6,6,5 10,3 3,10 15,2 1,30 30,1 olabilir

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [87]:
benimNumpyDizim.max()

29

In [88]:
benimNumpyDizim.min()

0

In [89]:
benimNumpyDizim[4] = 50

In [90]:
benimNumpyDizim

array([ 0,  1,  2,  3, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [91]:
benimNumpyDizim.max()

50

In [92]:
benimNumpyDizim.argmax()

4

In [93]:
benimNumpyDizim.shape

(30,)

In [94]:
benimNumpyDizim = benimNumpyDizim.reshape(5,6)

In [95]:
benimNumpyDizim

array([[ 0,  1,  2,  3, 50,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [96]:
benimNumpyDizim[3][2]

20

In [98]:
benimNumpyDizim.shape

(5, 6)