In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [5]:
benimDizim[3:8] = 5

In [6]:
benimDizim

array([ 0,  1,  2,  5,  5,  5,  5,  5,  8,  9, 10, 11, 12, 13, 14])

In [7]:
digerDizi = np.arange(0,25)

In [8]:
digerDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
slicingDizisi = digerDizi[4:9]

In [10]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [11]:
digerDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
slicingDizisi[:] = 700

In [13]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [14]:
digerDizi
#Görüldüğü gibi slicingDizisi üzerinde yapılan değişiklik digerDizi isimli diziyi de etkiledi(Listelerde böyle olmaz)

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [15]:
ornekDizi = np.arange(0,25)

In [16]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ornekDiziKopyasi = ornekDizi.copy()

In [18]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [21]:
ornekDiziKopyaSlicing[:] = 800

In [22]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [23]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [24]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
## Copy metodu sayesinde orjinal diziyi etkilemeden kopya dizi üzerinden işlem yapılabilir

# matrix

In [26]:
benimListem = [[10,20,30], [40,50,60],[70,80,90]]

In [27]:
benimMatrixDizim = np.array(benimListem)

In [28]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [29]:
benimMatrixDizim[0]

array([10, 20, 30])

In [30]:
benimMatrixDizim[0,1]

20

In [31]:
benimMatrixDizim[0][1]

20

In [32]:
benimMatrixDizim[1:,2]

array([60, 90])

In [33]:
benimMatrixDizim[1:,1:]

array([[50, 60],
       [80, 90]])

In [57]:
benimMatrixDizim[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [35]:
benimMatrixDizim[1:2,0:2]

array([[40, 50]])

In [36]:
yeniMatrix = np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])

In [37]:
yeniMatrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [38]:
yeniMatrix[[0,1,3]]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [11, 12, 13]])

In [39]:
yeniMatrix[[2,3]]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [40]:
#Bu şekilde bir indeksleme yapmak da mümkündür (Fancy Indexing)

# Operasyonlar

In [41]:
yeniBirDizi = np.random.randint(1,100,20)

In [42]:
yeniBirDizi

array([42, 48, 77, 60, 93, 82, 67, 97, 50, 21, 57, 39, 83, 34, 93,  2, 14,
       40, 32, 47])

In [43]:
sonucDizisi = yeniBirDizi > 24

In [44]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True])

In [45]:
yeniBirDizi

array([42, 48, 77, 60, 93, 82, 67, 97, 50, 21, 57, 39, 83, 34, 93,  2, 14,
       40, 32, 47])

In [46]:
yeniBirDizi[sonucDizisi]
#True değerler filtrelendi

array([42, 48, 77, 60, 93, 82, 67, 97, 50, 57, 39, 83, 34, 93, 40, 32, 47])

In [47]:
sonDizi = np.arange(0,25)

In [48]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [50]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [51]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [52]:
sonDizi / sonDizi

C:\Users\Yusuf\AppData\Local\Temp\ipykernel_14736\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [53]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [54]:
np.max(sonDizi)

24